name: CloudWatchAgentConfig
description: Configure the CloudWatch agent
schemaVersion: 1.0

phases:
  - name: build
    steps:
      - name: CloudWatchAgentConfig
        action: ExecuteBash
        inputs:
          commands:
            - amazon-cloudwatch-agent-ctl -a fetch-config -m ec2 -s -c ssm:/ONT-basecaller/aws-batch-container-instances-cloudwatch-agent-config
